# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single DevinAPieceOfSit
open_collective: # Replace with a single username
ko_fi: # Replace with a single DevinAPieceOfSit
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single DevinAPieceOfSit
issuehunt: # Replace with a single DevinAPieceOfSit
otechie: # Replace with a single  DevinAPieceOfSit
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
Cash.app/$Noxious15
